import { NextRequest, NextResponse } from 'next/server'

const CLAUDE_API_URL = 'https://api.anthropic.com/v1/messages'

export async function POST(request: NextRequest) {
  try {
    const CLAUDE_API_KEY = process.env.CLAUDE_API_KEY
    
    if (!CLAUDE_API_KEY || !CLAUDE_API_KEY.startsWith('sk-ant-')) {
      return NextResponse.json(
        { error: 'Claude API key not configured properly' },
        { status: 500 }
      )
    }

    const body = await request.json()
    const { prompt, platforms, formats, userData } = body

    if (!prompt) {
      return NextResponse.json(
        { error: 'Prompt is required' },
        { status: 400 }
      )
    }

    // Extract single platform (frontend sends array, we process one at a time)
    const platform = platforms?.[0] || 'instagram'
    const format = formats?.[0] || 'social-post'

    // ═══════════════════════════════════════════════════════════════════════
    // FIX: Reinforce single-platform generation instead of confusing Claude
    // with "create content for each platform" instructions
    // ═══════════════════════════════════════════════════════════════════════
    const enhancedPrompt = `${prompt}

CRITICAL INSTRUCTION: Generate content ONLY for ${platform.toUpperCase()}.
Do NOT create content for multiple platforms.
Do NOT include content for any other platform.
Do NOT include explanations, headers, or labels.
Start directly with the content text.
Output ONLY the final ${platform} content.`

    const claudeRequestBody = {
      model: 'claude-sonnet-4-20250514',
      max_tokens: 2000,
      messages: [{
        role: 'user',
        content: enhancedPrompt
      }]
    }

    const response = await fetch(CLAUDE_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': CLAUDE_API_KEY,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify(claudeRequestBody)
    })

    if (!response.ok) {
      const errorText = await response.text()
      console.error('Claude API error:', response.status, errorText)
      return NextResponse.json(
        { error: `Claude API error: ${response.status}`, details: errorText },
        { status: response.status }
      )
    }

    const data = await response.json()
    const generatedContent = data.content?.[0]?.text

    if (!generatedContent) {
      console.error('No content in Claude response:', JSON.stringify(data))
      return NextResponse.json(
        { error: 'No content generated by Claude' },
        { status: 500 }
      )
    }

    return NextResponse.json({
      content: generatedContent,
      platform,
      format,
      success: true,
      metadata: {
        contentLength: generatedContent.length,
        platform,
        format,
        timestamp: new Date().toISOString()
      }
    })

  } catch (error) {
    console.error('Server error:', error)
    return NextResponse.json(
      { error: 'Internal server error', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    )
  }
}
